name: ${name}
author: ${author}
version: ${version}
main: de.heisluft.ui.UncreativeItems
commands:
  items:
    description: open the items gui
    usage: /items [player]
  seturlskull:
    description: sets an url skull
    usage: /seturlskull <x> <y> <z> <url> [world]
  giveurlskull:
    description: gives an url skull
    usage: /giveurlskull [player] <url> [amount]